---
- name: Update apt-cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  register: result
  until: result is succeeded

- name: Upgrade all packages # noqa package-latest
  ansible.builtin.apt:
    upgrade: yes
    state: latest
  when: keep_packages_updated
  tags:
    - skip_ansible_lint

- name: Install some packages
  ansible.builtin.apt:
    name: "{{ ansible_infra_extra_packages }}"
    state: present
  register: result
  until: result is succeeded

- name: Install LazyDocker
  ansible.builtin.shell:
    cmd: curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
  args:
    creates: /usr/local/bin/lazydocker
  environment:
    DIR: /usr/local/bin

- name: "Set hostname to {{ ansible_infra_hostname }}"
  ansible.builtin.hostname:
    name: "{{ ansible_infra_hostname }}"

- name: "Set timezone to {{ ansible_infra_timezone }}"
  community.general.timezone:
    name: "{{ ansible_infra_timezone }}"

- name: "Permission share directories"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: ansible-infra
    group: ansible-infra
    mode: "u=rwX,g=rwX,o=rX"
    recurse: false
  loop: "{{ samba_shares }}"