---
- name: Infra
  hosts: all

  roles:
    ###
    ### Requirements
    ###
    - role: ansible-infra-users
      tags:
        - ansible-infra-users
        - ansible-infra

    - role: bertvv.samba
      tags:
        - samba
        - skip_ansible_lint

    - role: geerlingguy.docker
      when: ansible_architecture == "x86_64"
      tags:
        - docker
        - skip_ansible_lint

    - role: geerlingguy.docker_arm
      when: ansible_architecture == "aarch64"
      tags:
        - docker_arm
        - skip_ansible_lint

    ###
    ### Infra Roles
    ###
    - role: ansible-infra-general
      tags:
        - ansible-infra-general
        - ansible-infra

    - role: ansible-infra-docker
      tags:
        - ansible-infra-docker
        - ansible-infra

    ###
    ### Stacks
    ###

    - role: media
      tags:
        - media

    ###
    ### Applications
    ###

    - role: bazarr
      tags:
        - bazarr

    - role: cloudflare_ddns
      tags:
        - cloudflare_ddns

    - role: code-server
      tags:
        - code-server

    - role: ddns_updater
      tags:
        - ddns_updater

    - role: duplicati
      tags:
        - duplicati

    - role: glances
      tags:
        - glances

    - role: guacamole
      tags:
        - guacamole

    - role: healthchecks.io
      tags:
        - healthchecks.io

    - role: hello_world
      tags:
        - hello_world

    - role: jellyfin
      tags:
        - jellyfin

    - role: jellyseerr
      tags:
        - jellyseerr

    - role: minecraft-server
      tags:
        - minecraft-server

    - role: minecraft-bedrock-server
      tags:
        - minecraft-bedrock-server

    - role: nextcloud
      tags:
        - nextcloud

    - role: paperless-ngx
      tags:
        - paperless-ngx
        
    - role: portainer
      tags:
        - portainer

    - role: prowlarr
      tags:
        - prowlarr

    - role: qbittorrent
      tags:
        - qbittorrent

    - role: radarr
      tags:
        - radarr

    - role: route53_ddns
      tags:
        - route53_ddns

    - role: sonarr
      tags:
        - sonarr

    - role: speedtest-tracker
      tags:
        - speedtest-tracker

    - role: stats
      tags:
        - stats

    - role: syncthing
      tags:
        - syncthing

    - role: traefik
      tags:
        - traefik

    - role: vaultwarden
      tags:
        - vaultwarden

    - role: virtual-desktop
      tags:
        - virtual-desktop

    - role: watchtower
      tags:
        - watchtower
    - role: youtubedlmaterial
      tags:
        - youtubedlmaterial