---
- name: Infra
  hosts: all

  roles:
    ###
    ### Requirements
    ###
    - role: infra-users
      tags:
        - infra-users
        - infra

    - role: bertvv.samba
      tags:
        - samba
        - skip_ansible_lint

    - role: geerlingguy.docker
      when: ansible_architecture == "x86_64"
      tags:
        - docker
        - skip_ansible_lint

    - role: geerlingguy.docker_arm
      when: ansible_architecture == "aarch64"
      tags:
        - docker_arm
        - skip_ansible_lint