---
- name: Infra
  hosts: all

  roles:
    ###
    ### Requirements
    ###
    - role: ansible-infra-users
      tags:
        - ansible-infra-users
        - ansible-infra

    - role: bertvv.samba
      tags:
        - samba
        - skip_ansible_lint

    - role: geerlingguy.docker
      when: ansible_architecture == "x86_64"
      tags:
        - docker
        - skip_ansible_lint

    - role: geerlingguy.docker_arm
      when: ansible_architecture == "aarch64"
      tags:
        - docker_arm
        - skip_ansible_lint

    ###
    ### Infra Roles
    ###
    - role: ansible-infra-general
      tags:
        - ansible-infra-general
        - ansible-infra

    - role: ansible-infra-docker
      tags:
        - ansible-infra-docker
        - ansible-infra

    ###
    ### Stacks
    ###

    - role: media
      tags:
        - media

    ###
    ### Applications
    ###

    - role: bazarr
      tags:
        - bazarr

    - role: cloudflare_ddns
      tags:
        - cloudflare_ddns

    - role: code-server
      tags:
        - code-server

    - role: ddns_updater
      tags:
        - ddns_updater

    - role: glances
      tags:
        - glances

    - role: hello_world
      tags:
        - hello_world

    - role: jellyfin
      tags:
        - jellyfin

    - role: jellyseerr
      tags:
        - jellyseerr

    - role: nextcloud
      tags:
        - nextcloud
        
    - role: portainer
      tags:
        - portainer

    - role: prowlarr
      tags:
        - prowlarr

    - role: qbittorrent
      tags:
        - qbittorrent

    - role: radarr
      tags:
        - radarr

    - role: sonarr
      tags:
        - sonarr

    - role: stats
      tags:
        - stats

    - role: traefik
      tags:
        - traefik