---
watchtower_enabled: false

# Sets the 6 field cron schedule to use for checks and updates. This will check at 3am daily.
watchtower_cron_schedule: 0 0 3 * * *

# List of containers to exclude from watchtower for updates. 
# See https://containrrr.dev/watchtower/arguments/#filter_by_disabling_specific_container_names for more info
watchtower_exclude: "{{ virtual_desktop_container_name }}"

# Sets the Watchtower Docker start command. Different options can be supplied based on whether you want to receive
# notifications or not, some examples are provided below. See https://containrrr.dev/watchtower/arguments/ for more options.

# No notifications
watchtower_command: "--schedule '{{ watchtower_cron_schedule }}' --remove-volumes --disable-containers '{{ watchtower_exclude }}'"

# Email notifications
# watchtower_command: "--schedule '{{ watchtower_cron_schedule }}' --notifications 'email' --notification-email-from 'ansible@infra.com' --notification-email-to '{{ ansible_infra_email }}' --notification-email-server 'my.email.server.com' --notification-email-server-port '25' --notification-email-server-user 'email_username' --notification-email-server-password 'top-secret'"

# Slack notifications
# watchtower_command: "--schedule '{{ watchtower_cron_schedule }}' --notifications 'slack' --notification-slack-hook-url 'https://hooks.slack.com/services/xxx/yyyyyyyyyyyyyyy' --notification-slack-identifier 'infra'"

# specs
watchtower_memory: 1g

watchtower_container_name: "watchtower"
watchtower_image_name: "containrrr/watchtower"
watchtower_image_version: "latest"