---
- name: Start Wiregate
  block:
    - name: Create Wiregate directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items: 
        - "{{ wiregate_unbound_conf_directory }}"
        - "{{ wiregate_adguard_config_directory }}"
        - "{{ wiregate_adguard_data_directory }}"
        - "{{ wiregate_dashboard_config_directory }}"
        - "{{ wiregate_dashboard_data_directory }}"
        - "{{ wiregate_dashboard_db_directory }}"
        - "{{ wiregate_dashboard_iptables_directory }}"

    - name: Template Unbound config
      ansible.builtin.template:
        src: custom-unbound.conf.j2
        dest: "{{ wiregate_unbound_conf_directory }}/custom-unbound.conf"
      register: unbound_config

    - name: Template Adguard Home config
      ansible.builtin.template:
        src: AdGuardHome.yaml.j2
        dest: "{{ wiregate_adguard_config_directory }}/AdGuardHome.yaml"
      register: adguard_config

    - name: Create Private Docker network
      community.docker.docker_network:
        name: wiregate_private_network
        driver_options:
          com.docker.network.bridge.enable_icc: "true"
        attachable: true
        internal: false
        ipam_config:
          - subnet: 10.2.0.0/24
    
    - name: Unbound Docker Container
      community.docker.docker_container:
        name: "{{ wiregate_unbound_container_name }}"
        image: "{{ wiregate_unbound_container_image_name }}:{{ wiregate_unbound_container_image_version }}"
        pull: true
        volumes:
          - "{{ wiregate_unbound_conf_directory }}/custom-unbound.conf:/etc/unbound/custom.conf.d/custom-unbound.conf"
        networks:
          - name: wiregate_private_network
            ipv4_address: "10.2.0.200"
        memory: "{{ wiregate_unbound_memory }}"
        restart_policy: unless-stopped
    
    - name: Adguard Home Docker Container
      community.docker.docker_container:
        name: "{{ wiregate_adguard_container_name }}"
        image: "{{ wiregate_adguard_container_image_name }}:{{ wiregate_adguard_container_image_version }}"
        pull: true
        volumes:
          - "{{ wiregate_adguard_config_directory }}:/opt/adguardhome/conf"
          - "{{ wiregate_adguard_data_directory }}:/opt/adguardhome/work"
        networks:
          - name: wiregate_private_network
            ipv4_address: "10.2.0.100"
        memory: "{{ wiregate_adguard_memory }}"
        restart_policy: unless-stopped

    - name: Wiregate Dashboard Docker Container
      community.docker.docker_container:
        name: "{{ wiregate_dashboard_container_name }}"
        image: "{{ wiregate_dashboard_container_image_name }}:{{ wiregate_dashboard_container_image_version }}"
        pull: true
        capabilities:
          - NET_ADMIN
          - SYS_MODULE
        volumes:
          - "{{ wiregate_dashboard_config_directory }}:/etc/wireguard"
          - "{{ wiregate_dashboard_data_directory }}:/home/app/dashboard-config"
          - "{{ wiregate_dashboard_db_directory }}:/home/app/db"
          - "{{ wiregate_dashboard_iptables_directory }}:/home/app/Iptables"
        env:
          WG_DASH_USER: "{{ wiregate_dashboard_user }}"
          WG_DASH_PASS: "{{ wiregate_dashboard_pass }}"
          WG_DASH_SERVER_IP: "{{ wiregate_dashboard_server_ip }}"
          WG_DASH_DNS: 10.2.0.100, 10.2.0.100
          WG_DASH_IPTABLES_DNS: "10.2.0.100"
          WG_DASH_PEER_ENDPOINT_ALLOWED_IP: "0.0.0.0/0"
          WG_DASH_KEEP_ALIVE: "21"
          WG_DASH_MTU: "1420"
          WG_DASH_PORT_RANGE_STARTPORT: "{{ wiregate_dashboard_port_range_startpoint }}"
        ports:
          - "{{ wiregate_dashboard_port_mappings }}"
        sysctls:
          net.ipv4.ip_forward: 1
          net.ipv4.conf.all.src_valid_mark: 1
        networks:
          - name: wiregate_private_network
            ipv4_address: "10.2.0.3"
        memory: "{{ wiregate_dashboard_memory }}"
        restart_policy: unless-stopped
  when: wiregate_enabled is true

- name: Stop Wiregate
  block:
    - name: Stop Unbound
      community.docker.docker_container:
        name: "{{ wiregate_unbound_container_name }}"
        state: absent
    - name: Stop Adguard Home
      community.docker.docker_container:
        name: "{{ wiregate_adguard_container_name }}"
        state: absent
    - name: Stop Wiregate Dashboard
      community.docker.docker_container:
        name: "{{ wiregate_dashboard_container_name }}"
        state: absent
  when: wiregate_enabled is false